### ISSUE TITLE
Catch ether transferred by smart contract

### ISSUE THREAD

**Issue by muriloito-mb** [poonkt/eth-address-observer#12]
@Snitovets great job with this project.

But, from what I understand of the code, it can not identify ether transferred by smart contracts. Is my understanding correct?

**Comment by Snitovets** [comment]
I never tested this case, but probably you are right, it won't work that way. And it's an awesome idea to enhance functionality

**Comment by muriloito-mb** [comment]
thank you for confirming. 

nowadays it is very common transfer using smart contracts, mainly with the popularization of dapps and DeFI.

I already worked on a code to identify this kind of transactions for an exchange, but we identify a small lack recently and I am researching for some ideias how to improve the algorithm.

The main problem in my opinion is how the Geth provides the logs of a contract execution, it is not friendly.

**Comment by Snitovets** [comment]
You might consider to create smart-contract with similar logic. But probably it will be expensive in terms of gas

**Comment by muriloito-mb** [comment]
I can reproduce the problem, but I don`t know the what is the best solution yet. Geth has a poor RPC API to return the contract execution logs. I am thinking to use Parity to get these logs, but it takes too long to sync.

Probably you will face this king of problem too.

**Comment by Snitovets** [comment]
I dive deeply to this problem and figure out that only way to get info about any transfer are events. You can subscribe to logs which returns any information about past events. Also you should be acknowledged that transfer method contain event call and event follows ERC20 interface Transfer(address,address,uint256)

```javascript
"logs": [
      {
        "address": "0x0d8775f648430679a709e98d2b0cb6250d2887ef",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x000000000000000000000000d7afd4441fccc118b9207b0e136f4ef9319b3c79",
          "0x00000000000000000000000069d9e9aff57ec73582ad1ce441726dba7ea78fe0"
        ],
        "data": "0x0000000000000000000000000000000000000000000001054aefee8ba6d00000",
        "blockNumber": "0x5ff5dd",
        "transactionHash": "0x3265c1461d3f167c756fbc062ae3a2dc279b44a9c3ca2194271d4251cd0c1655",
        "transactionIndex": "0x1b",
        "blockHash": "0xc5e5a515898983d1370d40b03fc05ae08be861af746a1577796153a149a1bb20",
        "logIndex": "0xa",
        "removed": false
      }
    ]
```
For example: this is log for BAT token. 
topics[0] - means keccak hashed Transfer(address,address,uint256)
topics[1], topics[2] - zero padded until 32 bytes "from" and "to" addresses
data - hex representation of transfered amount

**Comment by Snitovets** [comment]
I will add token transfers support in next update
